// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "usart.h"
#include "lv_port_indev.h"

extern lv_indev_t *indev_button;

void ui_screen_loaded_cb(lv_event_t *e)
{
    lv_obj_t *target = lv_event_get_target(e);
    lv_group_t *g = lv_group_get_default();
    
    // 防止空指针异常
    if (!g) {
        g = lv_group_create();
        lv_group_set_default(g);
        lv_indev_set_group(indev_button, g);
        printf("Created new group in screen_loaded_cb\r\n");
    }
    
    // 清空当前导航组中的所有对象
    lv_group_remove_all_objs(g);
    printf("Screen loaded: %s\r\n", (target == ui_Screen1) ? "Screen1" : "Screen2");
    
    if (target == ui_Screen1) {
        lv_group_add_obj(g, ui_Button1);
        lv_group_focus_obj(ui_Button1);
        printf("Added Button1 to group\r\n");
    } 
    else if (target == ui_Screen2) {
        lv_group_add_obj(g, ui_Button4);
        lv_group_focus_obj(ui_Button4);
        printf("Added Button4 to group\r\n");
    }
}
